### ISSUE TITLE
Difference between caffe version and paper version VOC mAP

### ISSUE THREAD

**Issue by LovPe** [luuuyi/RefineDet.PyTorch#8]
i notice that there are gaps between caffe version and paper version in mAP do you know why?
How did you get the caffe version mAP? do you retrain the official code?

**Comment by luuuyi** [comment]
@luuuyi first, about the gap between my work and official implement version, I think it due to the DL framework. After I review the code and configuation in caffe verision, it has no difference between this two works.
Second, I get the mAP from the official homepage, but after retraining that work, I found the result is slightly low than the mAP which is declaimed on the homepage.

**Comment by LovPe** [comment]
ok thanks for reply
